### ISSUE TITLE
Implement environment variable YAML configuration

### ISSUE THREAD

**Issue by iameli** [streamplace/wheelhouse#30]
Right now environment variables are just hardcoded -- they need to be loaded from `wheelhouse.yaml` instead.

That structure should look like:

```
env:
  CSATS_DB_URL:
    - name: dev
       value: example1
    - name: stage
       value: example2
```

Additionally, this ticket should include using the values of those environment variables for kicking off subprocesses. Let's finish the issue.
